baseurl = "https://lilsus.xyz/"
languageCode = "en-us"
theme = 'terminal'
pagination.pagerSize = 5
enableGitInfo = true

[params]
  centerTheme = true
  showLastUpdated = false
  updatedDatePrefix = "Updated"

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Contents"

[languages]
  [languages.en]
    languageName = "English"
    title = "sus"

    [languages.en.params]
      subtitle = ""
      owner = "sus"
      keywords = ""
      copyright = "MIT"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "SUS"
        logoHomeLink = "/"
